use std::fs;
use std::path::{Path, PathBuf};
use serde::{Deserialize, Serialize};
use tauri::Manager;

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct RegistryEntry {
    pub id: String,
    pub name: String,
    pub path: String,
    pub parent_id: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
struct Registry {
    projects: Vec<RegistryEntry>,
}

fn sanitize_project_id(project_id: &str) -> String {
    project_id.replace(['/', '\\', '.'], "")
}

fn app_data_path(app: &tauri::AppHandle) -> Result<PathBuf, String> {
    app.path().app_data_dir().map_err(|e| format!("Could not resolve app data dir: {e}"))
}

fn registry_path(app: &tauri::AppHandle) -> Result<PathBuf, String> {
    Ok(app_data_path(app)?.join("registry.json"))
}

fn env_file_path(app: &tauri::AppHandle, project_id: &str) -> Result<PathBuf, String> {
    let safe_id = sanitize_project_id(project_id);
    if safe_id.is_empty() { return Err("Invalid project_id".to_string()); }
    Ok(app_data_path(app)?.join(format!("{safe_id}.env")))
}

fn read_registry_from_path(path: &Path) -> Result<Registry, String> {
    if !path.exists() { return Ok(Registry { projects: vec![] }); }
    let raw = fs::read_to_string(path).map_err(|e| format!("Failed to read registry: {e}"))?;
    serde_json::from_str(&raw).map_err(|e| format!("Failed to parse registry: {e}"))
}

fn write_registry_to_path(path: &Path, registry: &Registry) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("Failed to create dir: {e}"))?;
    }
    let json = serde_json::to_string_pretty(registry).map_err(|e| format!("Serialize error: {e}"))?;
    fs::write(path, json).map_err(|e| format!("Write error: {e}"))
}

#[tauri::command]
fn save_project_env(app: tauri::AppHandle, project_id: String, content: String) -> Result<(), String> {
    let path = env_file_path(&app, &project_id)?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("Failed to create dir: {e}"))?;
    }
    fs::write(&path, &content).map_err(|e| format!("Failed to write env file: {e}"))
}

#[tauri::command]
fn load_project_env(app: tauri::AppHandle, project_id: String) -> Result<String, String> {
    let path = env_file_path(&app, &project_id)?;
    if !path.exists() { return Ok(String::new()); }
    fs::read_to_string(&path).map_err(|e| format!("Failed to read env file: {e}"))
}

#[tauri::command]
fn register_project(app: tauri::AppHandle, entry: RegistryEntry) -> Result<(), String> {
    let path = registry_path(&app)?;
    let mut registry = read_registry_from_path(&path)?;
    registry.projects.retain(|p| p.id != entry.id);
    registry.projects.push(entry);
    write_registry_to_path(&path, &registry)
}

#[tauri::command]
fn unregister_project(app: tauri::AppHandle, project_id: String) -> Result<(), String> {
    let path = registry_path(&app)?;
    let mut registry = read_registry_from_path(&path)?;
    registry.projects.retain(|p| p.id != project_id);
    write_registry_to_path(&path, &registry)
}

#[tauri::command]
fn get_app_data_dir(app: tauri::AppHandle) -> Result<String, String> {
    app_data_path(&app).map(|p| p.to_string_lossy().into_owned())
}

#[tauri::command]
fn import_env_from_project(project_path: String) -> Result<String, String> {
    let env_path = Path::new(&project_path).join(".env");
    if !env_path.exists() { return Ok(String::new()); }
    fs::read_to_string(&env_path).map_err(|e| format!("Failed to read .env: {e}"))
}

#[tauri::command]
fn generate_shell_hook(app: tauri::AppHandle) -> Result<String, String> {
    let data_dir = app_data_path(&app)?.to_string_lossy().into_owned();
    Ok(format!(r#"
# ── dotenv-manager shell hook ─────────────────────────────────────────────
# Auto-generated by dotenv-manager. Paste into ~/.zshrc or ~/.bashrc.

_dotenv_manager_load() {{
  local registry="{data_dir}/registry.json"
  local data_dir="{data_dir}"
  [ -f "$registry" ] || return 0
  local matches=()
  while IFS= read -r line; do
    matches+=("$line")
  done < <(
    python3 - "$registry" "$PWD" <<'PYEOF'
import json, sys
registry_path, cwd = sys.argv[1], sys.argv[2]
with open(registry_path) as f:
    data = json.load(f)
cwd_parts = cwd.rstrip("/").split("/")
matched = []
for p in data.get("projects", []):
    proj_parts = p["path"].rstrip("/").split("/")
    depth = len(proj_parts)
    if cwd_parts[:depth] == proj_parts:
        matched.append((depth, p.get("parentId") or "null", p["id"]))
matched.sort(key=lambda x: x[0])
for depth, parent_id, pid in matched:
    print(f"{{depth}}:{{parent_id}}:{{pid}}")
PYEOF
  )
  [ ${{#matches[@]}} -eq 0 ] && return 0
  local loaded=()
  for entry in "${{matches[@]}}"; do
    local rest="${{entry#*:}}"
    local parent_id="${{rest%%:*}}"
    local project_id="${{rest#*:}}"
    if [ "$parent_id" != "null" ]; then
      local parent_file="$data_dir/${{parent_id}}.env"
      local already=0
      for lid in "${{loaded[@]}}"; do [ "$lid" = "$parent_id" ] && already=1 && break; done
      if [ $already -eq 0 ] && [ -f "$parent_file" ]; then
        set -a; source "$parent_file"; set +a
        loaded+=("$parent_id")
      fi
    fi
    local env_file="$data_dir/${{project_id}}.env"
    local already=0
    for lid in "${{loaded[@]}}"; do [ "$lid" = "$project_id" ] && already=1 && break; done
    if [ $already -eq 0 ] && [ -f "$env_file" ]; then
      set -a; source "$env_file"; set +a
      loaded+=("$project_id")
    fi
  done
}}

_dotenv_manager_load
if [[ -n "$ZSH_VERSION" ]]; then
  autoload -Uz add-zsh-hook
  add-zsh-hook chpwd _dotenv_manager_load
elif [[ -n "$BASH_VERSION" ]]; then
  PROMPT_COMMAND="_dotenv_manager_load${{PROMPT_COMMAND:+; $PROMPT_COMMAND}}"
fi
# ── end dotenv-manager shell hook ─────────────────────────────────────────
"#, data_dir = data_dir))
}

#[tauri::command]
fn check_gitignore_status(project_path: String) -> Result<String, String> {
    let gitignore = Path::new(&project_path).join(".gitignore");
    if !gitignore.exists() {
        return Ok("no_gitignore".to_string());
    }
    let content = fs::read_to_string(&gitignore)
        .map_err(|e| format!("Failed to read .gitignore: {e}"))?;
    let listed = content.lines().any(|line| {
        let l = line.trim();
        l == ".env" || l == "*.env" || l == ".env*"
    });
    if listed {
        Ok("listed".to_string())
    } else {
        Ok("not_listed".to_string())
    }
}

// ── Legacy commands (keep during migration) ───────────────────────────────
#[tauri::command]
fn read_file(path: String) -> Result<String, String> {
    fs::read_to_string(&path).map_err(|e| e.to_string())
}

#[tauri::command]
fn write_file(path: String, content: String) -> Result<(), String> {
    fs::write(&path, content).map_err(|e| e.to_string())
}

#[tauri::command]
fn path_exists(path: String) -> bool {
    Path::new(&path).exists()
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_dialog::init())
        .invoke_handler(tauri::generate_handler![
            read_file, write_file, path_exists,
            save_project_env, load_project_env,
            register_project, unregister_project,
            get_app_data_dir, generate_shell_hook,
            import_env_from_project, check_gitignore_status,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    fn temp_registry(dir: &TempDir) -> PathBuf {
        dir.path().join("registry.json")
    }

    #[test]
    fn sanitize_removes_slashes_and_dots() {
        assert_eq!(sanitize_project_id("abc/def\\ghi.jkl"), "abcdefghijkl");
    }

    #[test]
    fn sanitize_leaves_uuid_unchanged() {
        let uuid = "550e8400-e29b-41d4-a716-446655440000";
        assert_eq!(sanitize_project_id(uuid), uuid);
    }

    #[test]
    fn sanitize_empty_returns_empty() {
        assert_eq!(sanitize_project_id(""), "");
    }

    #[test]
    fn read_registry_returns_empty_when_missing() {
        let dir = TempDir::new().unwrap();
        let path = temp_registry(&dir);
        let reg = read_registry_from_path(&path).unwrap();
        assert!(reg.projects.is_empty());
    }

    #[test]
    fn write_and_read_registry_roundtrip() {
        let dir = TempDir::new().unwrap();
        let path = temp_registry(&dir);
        let entry = RegistryEntry {
            id: "abc-123".to_string(),
            name: "my-project".to_string(),
            path: "/home/user/project".to_string(),
            parent_id: None,
        };
        let registry = Registry { projects: vec![entry.clone()] };
        write_registry_to_path(&path, &registry).unwrap();
        let loaded = read_registry_from_path(&path).unwrap();
        assert_eq!(loaded.projects.len(), 1);
        assert_eq!(loaded.projects[0].id, "abc-123");
        assert_eq!(loaded.projects[0].name, "my-project");
        assert_eq!(loaded.projects[0].parent_id, None);
    }

    #[test]
    fn write_registry_creates_parent_dirs() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("nested/deep/registry.json");
        let registry = Registry { projects: vec![] };
        write_registry_to_path(&path, &registry).unwrap();
        assert!(path.exists());
    }

    #[test]
    fn read_registry_errors_on_invalid_json() {
        let dir = TempDir::new().unwrap();
        let path = temp_registry(&dir);
        fs::write(&path, "not valid json").unwrap();
        assert!(read_registry_from_path(&path).is_err());
    }
}
